### ISSUE TITLE
user in inbox not changing on first render

### ISSUE THREAD

**Issue by joshxfi** [joshxfi/umamin#39]
**Describe the bug**
Account/user's inbox does not change after signing out and then logging in with a different account but only changes after a reload.

**To Reproduce**
1. Login
2. Logout
3. Login with a different account
4. You'll see that the user in the unique link was from the one you previously logged in

**Expected behavior**
The user in the inbox should be the one that is currently logged in on first render

**Screenshots**
- logged in as `test` but previously logged in as `testuser`. 
![image](https://user-images.githubusercontent.com/69457996/180594765-6952005e-dd3d-456f-9077-4a64687a407e.png)

**Comment by princejoogie** [comment]
this is caused by the `getServerSideProps`. it only runs on page load. I think i previously had this working with no ssr. to fix this, you should use `useSession` which keeps track of the current user. the id of the user is accessible there. theres also a `status` in useSession that you will use to redirect to login

we can get rid of getserversideprops entirely

**Comment by joshxfi** [comment]
I see, I'll work on a fix, thanks!
